### ISSUE TITLE
year variable is sometimes character instead of integer

### ISSUE THREAD

**Issue by choisy** [choisy/gso#14]

**Comment by LucieContamin** [comment]
Sometimes the year is expressed as an interval like: "2011_2012", that's why the variable is sometimes character. We need to think of another way to express this interval.

**Comment by choisy** [comment]
The tables for which the `year` variable is a range of years, e.g. `2006-2008`, the `year` variable could remain a character (because of the `-`), but for all the other tables for which the `year` variable is defined by year, then it would be very useful that the `year` variable is always an integer and not a character.

**Comment by LucieContamin** [comment]
Fix in pull-request #36
